### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [MarkSherstan/MPU6050_Visualizer#5]
I noticed that in all your repositories the code for the MPU-6050 has while-loops to wait after a `Wire.requestFrom()`.

You may remove all these lines: `while(Wire.available() < 14);`
I counted nine of those lines.

Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by rijesha** [comment]
Yea. I agree.

**Comment by MarkSherstan** [comment]
Thank you @Koepel, I have made the updates in this repository with pull request #7 .
