### ISSUE TITLE
Fixing "Slider() has no valstep parameter" error msg 

### ISSUE THREAD

**Issue by slowrunner** [MarkSherstan/MPU6050_Visualizer#8]
In running magCalSlider.py on Dexter Industries Raspbian for Robots, I received the error:
`Slider() has no valstep parameter`

`pip3 freeze | grep matplotlib` reported matplotlib version 2.0.0
`sudo pip3 install --upgrade matplotlib` fixed the issue  (upgraded to version 3.0.3)

(Can mark issue solved/complete.)

**Comment by MarkSherstan** [comment]
Resolving issue as per comments above.
